import BarcodeScanner from "react-qr-barcode-scanner";
import { Scan } from "lucide-react";

const QRScannerModal = ({ onDetected }) => {
    return (
        <div className="relative flex flex-col items-center justify-center p-6 bg-slate-950 rounded-xl border border-slate-800 shadow-inner overflow-hidden w-full max-w-sm mx-auto my-4">

            {/* High-Tech Viewfinder Corners */}
            <div className="absolute top-4 left-4 w-8 h-8 border-t-2 border-l-2 border-blue-500 rounded-tl-lg z-10"></div>
            <div className="absolute top-4 right-4 w-8 h-8 border-t-2 border-r-2 border-blue-500 rounded-tr-lg z-10"></div>
            <div className="absolute bottom-4 left-4 w-8 h-8 border-b-2 border-l-2 border-blue-500 rounded-bl-lg z-10"></div>
            <div className="absolute bottom-4 right-4 w-8 h-8 border-b-2 border-r-2 border-blue-500 rounded-br-lg z-10"></div>

            {/* Scanner Container */}
            <div className="relative w-full aspect-square rounded-lg overflow-hidden bg-black shadow-lg">
                {/* Tailwind Magic: [&>div] and [&>video] forcefully override 
                    the inline styles generated by the third-party library 
                */}
                <div className="w-full h-full [&>div]:!w-full [&>div]:!h-full [&>div]:!pt-0 [&>video]:object-cover [&>video]:w-full [&>video]:h-full">
                    <BarcodeScanner
                        facingMode="environment"
                        onUpdate={(err, result) => {
                            if (result) {
                                onDetected(result.text);
                            }
                        }}
                    />
                </div>

                {/* Subtle scanning laser animation line */}
                <div className="absolute top-0 left-0 w-full h-0.5 bg-blue-500/50 shadow-[0_0_8px_2px_rgba(59,130,246,0.5)] animate-[scan_2s_ease-in-out_infinite]"></div>
            </div>

            <div className="mt-6 flex items-center gap-2 text-blue-400 font-medium text-sm animate-pulse tracking-wide uppercase">
                <Scan className="w-4 h-4" />
                <span>Scanning CDIIS Registry Tag...</span>
            </div>
        </div>
    );
};

export default QRScannerModal;
